# Generated by Django 5.0.14 on 2026-09-09 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0025_escapegame_currency_escapegame_price_cents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provider', models.CharField(choices=[('free_launch', 'Lancement gratuit (simulé)'), ('google_play', 'Google Play Billing')], max_length=16)),
                ('google_play_purchase_token', models.CharField(blank=True, default='', max_length=255)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('valid', 'Valide'), ('refunded', 'Remboursée')], default='valid', max_length=16)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('escape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='games.escapegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente de reversement'), ('paid', 'Reversée')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='monetization.purchase')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'escape'], name='monetizatio_user_id_3ec3f7_idx'),
        ),
    ]
