# Generated by Django 5.0.14 on 2026-09-09 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_escapegame_currency_escapegame_price_cents'),
        ('monetization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaywallImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paywall_impressions', to='games.escapegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paywall_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['escape'], name='monetizatio_escape__e2a056_idx')],
            },
        ),
    ]
