# Generated by Django 5.0.14 on 2025-08-19 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_alter_playsession_unique_together_and_more'),
        ('games', '0004_alter_escapegame_options_alter_escapestep_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=24)),
                ('escape', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='games.escapegame')),
            ],
        ),
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.escapegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'escape')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='games.escapegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'escape')},
            },
        ),
        migrations.DeleteModel(
            name='PlayerSession',
        ),
    ]
