# Generated by Django 5.0.14 on 2025-08-20 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_escapecompletion_playsession_rating_and_more'),
        ('games', '0004_alter_escapegame_options_alter_escapestep_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'escape'), name='uniq_user_escape_rating'),
        ),
    ]
