# Generated by Django 5.0.14 on 2025-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_alter_rating_options_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='current_step_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playsession',
            name='hints_used',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
