# Generated by Django 5.0.14 on 2025-08-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0006_playsession_current_step_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
    ]
