# Generated by Django 5.0.14 on 2026-07-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0010_alter_passwordresettoken_options_and_more'),
        ('engagement', '0010_playsession_play_time_seconds'),
    ]

    operations = [
    ]
