# Generated by Django 5.0.14 on 2026-07-17 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_verified_profiles(apps, schema_editor):
    """
    Comptes deja existants (reels et bots pas encore nettoyes) : on les marque
    verifies pour ne rien casser retroactivement. Seules les NOUVELLES
    inscriptions passeront par le flux de verification par email.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model('engagement', 'UserProfile')
    UserProfile.objects.bulk_create(
        [UserProfile(user_id=uid, email_verified=True) for uid in User.objects.values_list('id', flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0011_merge_20260717_1336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_verified_profiles, migrations.RunPython.noop),
    ]
