# Generated by Django 5.0.14 on 2026-07-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0011_merge_20260120_2001'),
        ('engagement', '0012_emailverificationtoken_userprofile'),
    ]

    operations = [
    ]
