# Generated by Django 5.0.14 on 2026-10-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0013_merge_20260720_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
