# Generated by Django 5.0.14 on 2026-10-09 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0015_purge_positions_gps_historiques'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_demande', models.EmailField(blank=True, default='', max_length=254)),
                ('username_au_moment_de_la_demande', models.CharField(blank=True, default='', max_length=150)),
                ('motif', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traitée'), ('annulee', 'Annulée')], default='en_attente', max_length=16)),
                ('demandee_le', models.DateTimeField(auto_now_add=True)),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('detail_traitement', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de suppression de compte',
                'verbose_name_plural': 'Demandes de suppression de compte',
                'ordering': ['-demandee_le'],
            },
        ),
    ]
