# Generated by Django 5.0.14 on 2026-10-09 08:51
#
# Depend volontairement de 0016_accountdeletionrequest plutot que de 0015 :
# les deux chantiers ont ete menes en parallele et, tous deux appuyes sur
# 0015, auraient produit deux feuilles dans le graphe de migrations, ce que
# Django refuse sans migration de fusion. Cette dependance impose l'ordre
# au lieu de laisser le probleme apparaitre au deploiement.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0016_accountdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playsession',
            name='server_play_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
