# Generated by Django 5.0.14 on 2025-08-13 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='end_code',
            field=models.CharField(default='0000', max_length=32),
        ),
        migrations.AddField(
            model_name='escapegame',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_escapes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escapegame',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='published', max_length=16),
        ),
        migrations.CreateModel(
            name='EscapeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('prompt', models.TextField(blank=True)),
                ('answer', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=50)),
                ('escape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='games.escapegame')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
