# Generated by Django 5.0.14 on 2025-08-14 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_escapegame_end_code_escapegame_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escapegame',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='escapestep',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='escapegame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='escapes/%Y/%m'),
        ),
        migrations.AddField(
            model_name='escapestep',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='escapestep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='escapes/steps/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escape_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published')], default='published', max_length=16),
        ),
    ]
