# Generated by Django 5.0.14 on 2025-08-19 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_escapegame_options_alter_escapestep_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escapegame',
            options={},
        ),
        migrations.AlterModelOptions(
            name='escapestep',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='escapegame',
            name='image',
        ),
        migrations.RemoveField(
            model_name='escapestep',
            name='description',
        ),
        migrations.RemoveField(
            model_name='escapestep',
            name='image',
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_escapes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='published', max_length=16),
        ),
    ]
