# Generated by Django 5.0.14 on 2025-08-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_escapegame_options_alter_escapestep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='GameStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('answer_type', models.CharField(choices=[('text', 'Texte libre'), ('mcq', 'Choix multiple')], default='text', max_length=10)),
                ('answer_text', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_index', models.PositiveIntegerField(blank=True, null=True)),
                ('hint', models.TextField(blank=True)),
                ('hint_penalty', models.IntegerField(default=0)),
                ('escape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_steps', to='games.escapegame')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='gamestep',
            constraint=models.UniqueConstraint(fields=('escape', 'order'), name='uniq_step_order_per_escape'),
        ),
    ]
