# Generated by Django 5.0.14 on 2025-08-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_escapegame_image_url_alter_escapegame_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escapegame',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text="Durée totale estimée pour terminer l'escape (en minutes).", verbose_name='estimated duration (min)'),
        ),
    ]
