# Generated by Django 5.0.14 on 2025-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_escapegame_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestep',
            name='final_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gamestep',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestep',
            name='rating_code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='gamestep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_last', True)), fields=('escape',), name='unique_last_step_per_escape'),
        ),
    ]
