# Generated by Django 5.0.14 on 2025-08-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_remove_gamestep_unique_last_step_per_escape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='penalize_wrong_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escapegame',
            name='wrong_answer_penalty',
            field=models.IntegerField(default=5),
        ),
    ]
