# Generated by Django 5.0.14 on 2025-08-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_escapegame_penalize_wrong_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='victory_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
