# Generated by Django 5.0.14 on 2025-09-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0007_playsession_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
