# Generated by Django 5.0.14 on 2025-08-14 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('games', '0003_alter_escapegame_options_alter_escapestep_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playsession',
            name='escape',
        ),
        migrations.RemoveField(
            model_name='playsession',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='escape',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.escapegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escape_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EscapeCompletion',
        ),
        migrations.DeleteModel(
            name='PlaySession',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddConstraint(
            model_name='playersession',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('user', 'escape'), name='unique_open_session_per_user_escape'),
        ),
    ]
