# Generated by Django 5.0.14 on 2026-07-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey",
                    models.CharField(
                        choices=[
                            ("parcours", "Parcours"),
                            ("application", "Application"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("escape", models.CharField(blank=True, default="", max_length=255)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "form_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("duree", models.CharField(blank=True, default="", max_length=32)),
                ("indices", models.CharField(blank=True, default="", max_length=32)),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("os", models.CharField(blank=True, default="", max_length=32)),
                ("lang", models.CharField(blank=True, default="", max_length=16)),
                (
                    "etape_abandon",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("reponses", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session", ""), _negated=True),
                fields=("session", "survey", "escape"),
                name="uniq_session_survey_escape",
            ),
        ),
    ]
