# Generated by Django 5.0.14 on 2025-08-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gamestep_final_message_gamestep_is_last_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escapegame',
            name='end_code',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
