# Generated by Django 5.0.14 on 2025-08-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_escapegame_end_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escapegame',
            name='end_code',
        ),
    ]
