# Generated by Django 5.0.14 on 2025-08-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_escapegame_end_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamestep',
            name='unique_last_step_per_escape',
        ),
        migrations.RemoveField(
            model_name='gamestep',
            name='is_last',
        ),
        migrations.RemoveField(
            model_name='gamestep',
            name='rating_code',
        ),
        migrations.AddField(
            model_name='escapegame',
            name='end_code',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='gamestep',
            name='is_final',
            field=models.BooleanField(default=False, help_text="Si activé, une bonne réponse à cette étape termine l'escape."),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamestep',
            name='final_message',
            field=models.TextField(blank=True, help_text="Message montré quand le joueur termine l'escape via cette étape."),
        ),
    ]
