# Generated by Django 5.0.14 on 2025-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_escapegame_victory_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='escapegame',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('pending', 'pending'), ('rejected', 'rejected'), ('published', 'published')], default='draft', max_length=20),
        ),
    ]
