# Generated by Django 5.0.14 on 2025-09-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_escapegame_reject_reason_alter_escapegame_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestep',
            name='expected_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestep',
            name='number_tolerance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gamestep',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Texte libre'), ('mcq', 'Choix multiple'), ('numeric', 'Numeric')], default='text', max_length=10),
        ),
    ]
