# Generated by Django 5.0.14 on 2025-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gamestep_expected_number_gamestep_number_tolerance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestep',
            name='match_left',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gamestep',
            name='match_pairs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gamestep',
            name='match_right',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gamestep',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Texte libre'), ('mcq', 'Choix multiple'), ('numeric', 'Numeric'), ('matching', 'Association')], default='text', max_length=10),
        ),
    ]
