# Generated by Django 5.0.14 on 2025-09-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_gamestep_match_left_gamestep_match_pairs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestep',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Texte libre'), ('mcq', 'Choix multiple'), ('numeric', 'Numeric'), ('matching', 'Association'), ('narration', 'Narration')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='gamestep',
            name='expected_number',
            field=models.FloatField(blank=True, help_text='(Optionnel) Non utilisé par le moteur actuel.', null=True),
        ),
        migrations.AlterField(
            model_name='gamestep',
            name='number_tolerance',
            field=models.FloatField(blank=True, default=0, help_text='(Optionnel) Non utilisé par le moteur actuel.', null=True),
        ),
    ]
