# Generated by Django 5.0.14 on 2025-09-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_gamestep_answer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestep',
            name='hints',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
