# Generated by Django 5.0.14 on 2025-09-12 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_gamestep_hints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs autorisés à voir un escape privé.', related_name='allowed_private_escapes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escapegame',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
