# Generated by Django 5.0.14 on 2026-07-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_escapegame_allowed_users_escapegame_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestep',
            name='show_location',
            field=models.BooleanField(default=True, help_text='Afficher le point sur la carte au joueur'),
        ),
    ]
