# Generated by Django 5.0.14 on 2026-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0019_gamestep_show_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="escapegame",
            name="age_rating",
            field=models.CharField(
                choices=[
                    ("3", "3 ans et +"),
                    ("12", "12 ans et +"),
                    ("18", "18 ans et +"),
                ],
                default="3",
                help_text="Âge minimum conseillé (type PEGI).",
                max_length=2,
            ),
        ),
    ]
