# Generated by Django 5.0.14 on 2026-08-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_escapegame_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='image_credit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gamestep',
            name='image_credit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
