# Generated by Django 5.0.14 on 2026-08-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_escapegame_image_credit_gamestep_image_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestep',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Texte libre'), ('mcq', 'Choix multiple'), ('numeric', 'Numeric'), ('matching', 'Association'), ('cesar', 'Code de César'), ('narration', 'Narration')], default='text', max_length=10),
        ),
    ]
