# Generated by Django 5.0.14 on 2026-08-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_alter_gamestep_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Fond sonore joué en boucle pendant la partie (≥ 1 min).', null=True),
        ),
    ]
