# Generated by Django 5.0.14 on 2026-09-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_gamestep_location_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='escapegame',
            name='price_cents',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
