# Generated by Django 5.0.14 on 2026-10-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_escapegame_currency_escapegame_price_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestep',
            name='answer_text_alt',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
